### PR TITLE
[Better Error] Improve error raised when authentication fails.

### PR DESCRIPTION
**Pull request by mlendale**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29)

### CODE REVIEW

**Comment by pcorpet** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! undefined

---

*[emploi_store/__init__.py, line 39 at r1](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29#-LG-G39y2f_wO5nBdGUz:-LG-G39y2f_wO5nBdGV-:bxzwtq7) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/eb724f63bb358afd8e597a5346330d5fc3ef2b7e/emploi_store/__init__.py#L39)):*
> ```Python
> 
> import requests
> from requests.exceptions import HTTPError
> ```

please only import modules.

---

*[emploi_store/__init__.py, line 91 at r1](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29#-LG-GD0xDmYV1sWr8UrI:-LG-GD0xDmYV1sWr8UrJ:b-ajhk4w) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/eb724f63bb358afd8e597a5346330d5fc3ef2b7e/emploi_store/__init__.py#L91)):*
> ```Python
>             auth_request.raise_for_status()
>         except HTTPError as error:
>             raise ValueError('Autentication failed: {}'.format(error))
> ```

`raise ValueError('Authentication failed') from error`

---

*[tests/emploi_store_test.py, line 48 at r1](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29#-LG-GiuL9mA0xAFUIyg5:-LG-GiuL9mA0xAFUIyg6:b-nqo9fk) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/eb724f63bb358afd8e597a5346330d5fc3ef2b7e/tests/emploi_store_test.py#L48)):*
> ```Python
>     def test_access_fails(self, mock_requests):
>         """Test the access_token method."""
>         mock_requests.post.return_value = mock.MagicMock()
> ```

hmm, actually this one is useless (mock_requests is a MagicMock so post as well)

---

*[tests/emploi_store_test.py, line 49 at r1](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29#-LG-GNX4DutUz-JItl3R:-LG-GNX55M7OMP9rp1T8:b6cdi2l) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/eb724f63bb358afd8e597a5346330d5fc3ef2b7e/tests/emploi_store_test.py#L49)):*
> ```Python
>         """Test the access_token method."""
>         mock_requests.post.return_value = mock.MagicMock()
>         mock_requests.post.return_value.status_code = 400
> ```

The right thing to mock is actually the side_effect of raise_for_status:

`mock_requests.post().raise_for_status.side_effect = exceptions.HTTPError`

At this point, please add a TODO to use the requests_mock package for testing.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29#-:-LG-H1NO52-qhmYdEyg0:bnfp4nl)*

**Comment by mlendale** [comment]
Review status: :shipit: complete! undefined

---

*[emploi_store/__init__.py, line 39 at r1](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29#-LG-G39y2f_wO5nBdGUz:-LG0fWpZ4dDjsZ7OWM-J:b-896fix) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/eb724f63bb358afd8e597a5346330d5fc3ef2b7e/emploi_store/__init__.py#L39)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

please only import modules.
</blockquote></details>

Done.

---

*[emploi_store/__init__.py, line 91 at r1](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29#-LG-GD0xDmYV1sWr8UrI:-LG0fbLD2VBbNzNISrVk:bynrpzm) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/eb724f63bb358afd8e597a5346330d5fc3ef2b7e/emploi_store/__init__.py#L91)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

`raise ValueError('Authentication failed') from error`
</blockquote></details>

Actually raise from is only in Python3.

---

*[tests/emploi_store_test.py, line 48 at r1](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29#-LG-GiuL9mA0xAFUIyg5:-LG0j4pWCET-BQ7HJulM:b-896fix) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/eb724f63bb358afd8e597a5346330d5fc3ef2b7e/tests/emploi_store_test.py#L48)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

hmm, actually this one is useless (mock_requests is a MagicMock so post as well)
</blockquote></details>

Done.

---

*[tests/emploi_store_test.py, line 49 at r1](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29#-LG-GNX4DutUz-JItl3R:-LG0j5EVAVITBdcnsJGr:b-896fix) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/eb724f63bb358afd8e597a5346330d5fc3ef2b7e/tests/emploi_store_test.py#L49)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

The right thing to mock is actually the side_effect of raise_for_status:

`mock_requests.post().raise_for_status.side_effect = exceptions.HTTPError`

At this point, please add a TODO to use the requests_mock package for testing.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29)*

**Comment by pcorpet** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! undefined

---

*[tests/emploi_store_test.py, line 54 at r2](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29#-LG4Ekhp7l_5-yv4vyKw:-LG4Ekhp7l_5-yv4vyKx:bunjc6e) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/f5cea6b4f4c8ddc68ba9cbe38bfc94f3313b32f0/tests/emploi_store_test.py#L54)):*
> ```Python
>         mock_requests.post().raise_for_status.side_effect = http_error
> 
>         self.assertRaises(ValueError)
> ```

You're not testing much here

---


*Comments from [Reviewable](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29)*

**Comment by mlendale** [comment]
Review status: :shipit: complete! undefined

---

*[tests/emploi_store_test.py, line 54 at r2](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29#-LG4Ekhp7l_5-yv4vyKw:-LG4YwCh8KOWioEXxnlJ:b-896fix) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/f5cea6b4f4c8ddc68ba9cbe38bfc94f3313b32f0/tests/emploi_store_test.py#L54)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

You're not testing much here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/bayesimpact/python-emploi-store/29)*

**Pull request merged**
