### PR TITLE
Use partenaire realm as recommended by https://www.emploi-store-dev.fr/portail-developpeur-cms/home/catalogue-des-api/documentation-des-api/utiliser-les-api/client-credentials-grant.html.

### PR DESCRIPTION
**Pull request by pcorpet**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/python-emploi-store/12)

### CODE REVIEW

**Comment by pcorpet** [comment]
@florianriche FYI

**Comment by pcorpet** [comment]
+@pnbt

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/python-emploi-store/12#-:-Kf7EEij6YovhI6SO9Ri:bfnzgui)*

**Comment by pnbt** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/python-emploi-store/12)*

**Comment by pnbt** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/python-emploi-store/12#-:-Kf7NHBSAxkvGaMmwjAx:bnfp4nl)*

**Comment by pnbt** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/python-emploi-store/12)*

**Pull request merged**
