### PR TITLE
Prepare for PyPi distribution.

### PR DESCRIPTION
**Pull request by pcorpet**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/python-emploi-store/2) &emsp; Multiple assignees:&emsp;@dedan&nbsp;<a href="/bayesimpact/python-emploi-store/pulls/assigned/dedan">dedan</a>,&emsp;@florianjourda&nbsp;<a href="/bayesimpact/python-emploi-store/pulls/assigned/florianjourda">florianjourda</a>

### CODE REVIEW

**Comment by pcorpet** [comment]
+@dedan +@florianjourda 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/python-emploi-store/2#-:-KEmdBGvULM_T-dLZRC8:793040211)*

**Comment by dedan** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[setup.cfg, line 2 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/python-emploi-store/2#-KEmjV3vTDgAf7za4sLG:-KEmjV3vTDgAf7za4sLH:955034966) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/b43132212975ba0fb1198f7f78efd20e3449079d/setup.cfg#L2)):*
did this work when pushing to pypi? I tried that for fex and did not manage to get the readme displayed

---

*[setup.py, line 4 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/python-emploi-store/2#-KEmjQJy5lPWpuRino1d:-KEmjQJy5lPWpuRino1e:304921616) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/b43132212975ba0fb1198f7f78efd20e3449079d/setup.py#L4)):*
you can also add the license to this setup

---

*[setup.py, line 12 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/python-emploi-store/2#-KEmjIXSmbadIXpkIp2A:-KEmjIXTT76zU6Pg3wUW:176007395) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/b43132212975ba0fb1198f7f78efd20e3449079d/setup.py#L12)):*
Is this something we will have to update with each version?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/python-emploi-store/2#-:-KEmjd1CbCGjcWKayhP5:1417088721)*

**Comment by pcorpet** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[setup.py, line 4 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/python-emploi-store/2#-KEmjQJy5lPWpuRino1d:-KEodZHco1hM6vQ39PJx:-499146009) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/b43132212975ba0fb1198f7f78efd20e3449079d/setup.py#L4)):*
Done.

---

*[setup.py, line 12 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/python-emploi-store/2#-KEmjIXSmbadIXpkIp2A:-KEobsaMaJhGIqInMHPK:-123376744) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/b43132212975ba0fb1198f7f78efd20e3449079d/setup.py#L12)):*
I believe so. I moved it to a var up there. I admit I just folllowed http://peterdowns.com/posts/first-time-with-pypi.html blindly.

---

*[setup.cfg, line 2 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/python-emploi-store/2#-KEmjV3vTDgAf7za4sLG:-KEobjbf6T0rArSM4ywl:1646411458) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/b43132212975ba0fb1198f7f78efd20e3449079d/setup.cfg#L2)):*
Didn't get it to display either :-( I'll look around a bit more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/python-emploi-store/2)*

**Comment by pcorpet** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[setup.cfg, line 2 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/python-emploi-store/2#-KEmjV3vTDgAf7za4sLG:-KEoil9rcOhQ91H6Mc0N:-1217481688) ([raw file](https://github.com/bayesimpact/python-emploi-store/blob/b43132212975ba0fb1198f7f78efd20e3449079d/setup.cfg#L2)):*
I tried to use pypandoc as recommended on the bug opened on PyPi but it's very big and makes the installation very heavy. So let's drop it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/python-emploi-store/2)*

**Pull request merged**
